---
- name: Clean node and data directory
  hosts: all
  tasks:
    - name: Clean launch directory
      file:
        path: "{{ ansible_env.HOME }}/launch"
        state: absent
      tags:
        - clean

    - name: Clean node directory
      file:
        path: "{{ ansible_env.HOME }}/node"
        state: absent
      tags:
        - clean

    - name: Clean Heimdall home directory
      file:
        path: "{{ ansible_env.HOME }}/.heimdalld"
        state: absent
      tags:
        - heimdall
        - clean

    - name: Clean Bor home directory
      file:
        path: "{{ ansible_env.HOME }}/.bor"
        state: absent
      tags:
        - bor
        - clean

    - name: Remove heimdall symlink
      file:
        path: "/usr/bin/heimdalld"
        state: absent
      become: true

    - name: Remove bridge symlink
      file:
        path: "/usr/bin/bridge"
        state: absent
      become: true

    - name: Remove bridge symlink
      file:
        path: "/usr/bin/bridge"
        state: absent
      become: true

    - name: Remove bor symlink
      file:
        path: "/usr/bin/bor"
        state: absent
      become: true

    - name: Remove bootnode symlink
      file:
        path: "/usr/bin/bootnode"
        state: absent
      become: true

    - name: Remove heimdallcli symlink
      file:
        path: "/usr/bin/heimdallcli"
        state: absent
      become: true
